AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageUri:
    Type: String

Resources:
# ============================================================
# MESSAGING AND STREAMING 
# ============================================================
  KinesisVideoStream:
    Type: AWS::KinesisVideo::Stream
    Properties:
      DataRetentionInHours: 20
      MediaType: "image/jpeg"
      Name: !Sub "${AWS::StackName}-kinesis-vs"
      Tags: 
        - Key: Project
          Value: Industrial-AI
  
  SimpleQueueService:
    Type : "AWS::SQS::Queue"
    Properties: 
       QueueName: !Sub "${AWS::StackName}-alerts-queue"
       VisibilityTimeout: 30
       MessageRetentionPeriod: 1209600  #dedicated for industrial system 
       SqsManagedSseEnabled: true #encryption at-rest 
       RedrivePolicy:
        deadLetterTargetArn : !GetAtt DLQ.Arn
        maxReceiveCount : 5 #five attempts
       Tags:
        - Key: Project
          Value: Industrial-AI

# ============================================================
# STORAGE AND DATABASES
# ============================================================
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-data-bucket"

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: infra-admin
      MasterUserPassword: infra-admin-password 
      VPCSecurityGroups: #we are waiting for VPC Net Configuration 
      DBSubnetGroupName: #we are waiting for VPC Net Configuration 
      PubliclyAccessible: false 

# ============================================================
# Container Registry and Services  
# ============================================================
  ECRInferenceContainer:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${AWS::StackName}-preprocessing"
      ImageScanningConfiguration:
          ScanOnPush: true
      ImageTagMutability: MUTABLE 
      LifecyclePolicy: 
          LifecyclePolicyText:  |
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "description": "Keep only last 5 images",
                  "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
                }
              ]
            }

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: industrial-ai-cluster

  ECSCapacityProviderAssociation:    
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders: 
          - FARGATE
          - FARGATE_SPOT
      DefaultCapacityProviderStrategy: 
        - CapacityProvider: FARGATE
          Base: 1
          Weight: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - Name: inference_process 
          Image: !Ref ContainerImage
          Essential: true
          PortMappings:
            - ContainerPort: 80
      Cpu: "2048"
      ExecutionRoleArn: arn:aws:iam::YOUR_ACCOUNT_ID:role/ecsTaskExecutionRole 
      Family: preprocessing-training-task
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSCluster
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1 
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration: #we are waiting for VPC Net Configuration 


# ============================================================
# Machine Learning 
# ============================================================

Outputs:
  KinesisVSName:
    Value: !Ref KinesisVideoStream
  
  S3BucketName:
    Value: !Ref S3Bucket

  ECSClusterName:
    Value: !Ref ECSCluster
  
  ECSServiceName:
    Value: !Ref ECSService 